---
### Enable zram swap
- name: Copy zram setup script
  become: true
  copy:
    src: setup-zram-swap.sh
    dest: /usr/local/sbin/setup-zram-swap.sh
    owner: root
    group: root
    mode: 0744

- name: Copy zram-swap systemd service file
  become: true
  copy:
    src: zram-swap.service
    dest: /etc/systemd/system/zram-swap.service
    owner: root
    group: root
    mode: 0644

- name: Enable zram-swap systemd service
  become: true
  command: systemctl enable zram-swap
  args:
    creates: /etc/systemd/system/multi-user.target.wants/zram-swap.service

### tweak touchpad pressure for libinput

- name: Ensure /etc/libinput exists
  become: true
  file:
    path: /etc/libinput
    state: directory

- name: Copy libinput touchpad pressure tweak file
  become: true
  copy:
    src: libinput-local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks

### keyboard backlight

- name: Ensure "leds" group exists
  become: true
  group:
    name: leds

- name: Ensure login user is in "leds" group
  become: true
  command: "usermod -aG leds {{ login_user }}"

- name: Copy pixelbook udev rules file
  become: true
  copy:
    src: keyboard-backlight-udev.rules
    dest: /lib/udev/rules.d/99-pixelbook.rules

- name: Copy brightness control script
  become: true
  copy:
    src: eve-keyboard-brightness.sh
    dest: /usr/local/bin/eve-keyboard-brightness.sh
    mode: 0755


### map Chromebook specific keys to functional keyboard mappings
- name: Copy keyboard hwdb file to remap keyboard
  become: true
  template:
    src: 60-keyboard.hwdb.j2
    dest: /lib/udev/hwdb.d/60-keyboard.hwdb
    mode: 0600
    owner: root
    group: root

- name: Update hwdb to load keyboard rules
  become: true
  command: "udevadm hwdb --update"

- name: Trigger udev to apply keyboard rules
  become: true
  command: "udevadm trigger"

## generate keyd configurations for use on Chromebooks (https://github.com/WeirdTreeThing/cros-keyboard-map)

- name: clone WeirdTreeThing source
  git:
    repo: 'https://github.com/WeirdTreeThing/cros-keyboard-map'
    version: "main"
    dest: "{{ keymap_workdir }}"

- name: execute installation script
  become: true
  command: "./install.sh"