---
- name: Create working dir to build packages
  become: true
  file:
    path: "{{ main_workdir }}"
    mode: 0777
    state: directory

###### Install WeirdTreeThing Linux Audio Setup (https://github.com/WeirdTreeThing/chromebook-linux-audio)

- name: clone WeirdTreeThing source
  git:
    repo: 'https://github.com/WeirdTreeThing/chromebook-linux-audio'
    version: "main"
    dest: "{{ cla_workdir }}"

- name: execute installation script
  become: true
  command: "./setup_audio"