---
- hosts: all

  tasks:
  - name: Install pre-requisites 
    include_role:
      name: common 

  - name: Install Chrultrabook kernel and sound setup files
    include_role:
      name: eve-audio

  - name: Install ChromeOS X11 touchpad driver
    include_role:
      name: eve-touchpad

  - name: Install misc tweaks
    include_role: 
      name: eve-tweaks
